---
#
# Ansible managed
#
repository:
  description: Install stratis and carves pools and filesystems.
  homepage: https://buluma.github.io/
  topics: stratis, storage, ansible, molecule, tox, playbook
